### ISSUE TITLE
connection failure после обновления страницы

### ISSUE THREAD

**Issue by ashlkv** [vitkarpov/yet-another-todo#1]
После обновления страницы случается connection failure, приходится перезапускать node.
В консоли браузера ошибки вида Not allowed to load local resource: blob:null/14d3a33e-17cc-4c9c-a523-370bd6fd2046

**Comment by vitkarpov** [comment]
@ashyashy 

Поправил багу с перезагрузкой и ряд других.
- `npm i`
- `grunt`

Устанавливаем зависимости, собираем и запускам веб-сервер. Дальше идем на `localhost:8000` — должен отобразиться интерфейс.

После изменения тасков в списке и перезагрузки страницы состояние должно сохраняться, пока работает веб-сервер (никакого бекенда нет, все сохраняется в оперативной памяти, пока работает нода)
