### ISSUE TITLE
Не собирается проект из-за новой ноды 0.12.2

### ISSUE THREAD

**Issue by raining** [vitkarpov/yet-another-todo#2]
Проект не собирается.
`$ node -v`
`v0.12.2`

Выдает 

`$ make all`

``` javascript
npm i
node_modules/.bin/grunt
Running "concat:css" (concat) task
File "dist/noscript-stub.css" created.

Running "concat:js" (concat) task
File "dist/noscript-stub.js" created.

Running "yate:dist" (yate) task
Warning: Cannot define property:48, object is not extensible. Use --force to continue.

Aborted due to warnings.
make: *** [grunt] Error 3
```

Нашла, что это из-за того что grunt не работает со старой нодой
https://github.com/gruntjs/grunt-contrib-jasmine/issues/97

**Comment by vitkarpov** [comment]
Похоже, будто сам `yate` не компилируется под новой нодой.
Надо попробовать собрать шаблон любой на новой ноде:

```
yate hello.yate > hello.js
```

**Comment by raining** [comment]
Получилось выполнить эту команду, yate под новой нодой работает. Я пыталась вручную собрать типа `yate views/app/app.yate > dist/noscript-stub.yate.js`, но может не тот файл указала. Что следует делать в таком случае? Очень нужно собрать и посмотреть как работает проект.

**Comment by vitkarpov** [comment]
Сейчас разберемся :)

**Comment by vitkarpov** [comment]
Попробуй переключить на коммит https://github.com/vitkarpov/yet-another-todo/commit/d7301ab8d907a91d1e00f8ad3691b9b2178ad95f

Проблема в `grunt-yate`, а точнее `temporary`, который он использует. Этот модуль работает под ноду начиная с версии 0.0.8 — обновился на него, в своем форке `grunt-yate`.

Сделаю pr в `grunt-yate`, потом обновлюсь у себя.

**Comment by vitkarpov** [comment]
https://github.com/Lapple/grunt-yate/pull/5

**Comment by vitkarpov** [comment]
пул реквест вмерджился, обновил `grunt-yate`. Собрал `v1.0.1`

```
npm install noscript-todo
```
