### ISSUE TITLE
Падает на таске exec:server

### ISSUE THREAD

**Issue by raining** [vitkarpov/yet-another-todo#3]
Запускала проект после починки проблемы https://github.com/vitkarpov/yet-another-todo/issues/2.
(заново склонировала поэтому старые проблемы исключены).

Теперь возникает другая: проект собирается, захожу по адресу `localhost:8000` и в консоль кидается

``` javascript
Running "exec:server" (exec) task
Server listening at 8000 port
>> events.js:85
>>       throw er; // Unhandled 'error' event
>>             ^
>> Error: ENOENT, open 'path/to/project/yet-another-todo/dist/noscript-stub.css'
>>     at Error (native)
>> Exited with code: 1.
Warning: Task "exec:server" failed. Use --force to continue.

Aborted due to warnings.

```

В интерфейсе соответственно ничего не видно и в консоль браузера кидаются ошибки типа `GET http://localhost:8000/ net::ERR_CONNECTION_REFUSED`

**Comment by vitkarpov** [comment]
Поменял название статичных файликов, которые генерирует grunt, а в `index.html` забыл изменить — поэтому падал сервере, при попытке прочитать файла, которого нет.

Поправил в `v1.0.2`

**Comment by raining** [comment]
Теперь все запустилось) Спасибо огромное за оперативность решения!

**Comment by vitkarpov** [comment]
:+1:
