### ISSUE TITLE
Подключен обфусцированный noscript

### ISSUE THREAD

**Issue by raining** [vitkarpov/yet-another-todo#4]
Это скорее даже не проблема, а просьба подключить не обфуцированный noscript для простоты отладки.

**Comment by vitkarpov** [comment]
+1

Заодно обновлю ns

**Comment by vitkarpov** [comment]
https://github.com/vitkarpov/yet-another-todo/pull/5

**Comment by vitkarpov** [comment]
- обновил ноускрипт + внес соответствующие изменения для новой версии
- подключил неминифицированный скрипт
- немного осовременил с бутстрапом

**Comment by vitkarpov** [comment]
v1.1.0

**Comment by raining** [comment]
спасибо!
